# This is the name of my library program
LIBRARY = libft.a
# These are the source files and the associated object files(can be blank)
SRC = ft_isalnum.c ft_isalpha.c ft_isacii.c 
# Continue adding all of the SRC files
SRC += ft_isdigit.c ft_isprint.c ft_memset.c
SRC += ft_bzero.c ft_memcpy.c ft_memmove.c
SRC += ft_strlcpy.c ft_strlcat.c ft_toupper.c
SRC += ft_tolower.c ft_strchr.c ft_strncmp.c
SRC += ft_memchr.c ft_memcmp.c ft_strnstr.c
SRC += ft_atoi.c ft_calloc.c ft_strdup.can
# Transformar todos os source files em object files
# Object files são a representação binária de um programa
OBJ = $(SRC:.c=.o)
# Escolher o compilador e as flags que queremos usar
CC = Não sei qual ainda mas seria o gcc?
CFLAGS = -Wall -Wextra -Werror